# Generated by Django 2.1.5 on 2021-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='gre_score',
            field=models.IntegerField(default=150),
        ),
    ]
