# Generated by Django 2.1.5 on 2021-04-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_siteuser_gre_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='gre_score',
            field=models.IntegerField(),
        ),
    ]
