# Generated by Django 2.1.5 on 2021-04-11 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210411_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='gre_score',
            field=models.IntegerField(default=140, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
    ]
