# Generated by Django 2.1.5 on 2021-04-11 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210411_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='gre_score',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='gre_awa_score',
            field=models.DecimalField(decimal_places=1, default=3.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)]),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='gre_quant_score',
            field=models.IntegerField(default=152, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='gre_verbal_score',
            field=models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
    ]
