# Generated by Django 2.1.5 on 2021-04-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210411_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='first_name',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='intended_semester',
            field=models.CharField(default='F', max_length=5),
        ),
    ]
