# Generated by Django 2.1.5 on 2021-04-11 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210411_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='gre_awa_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=3.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)]),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='gre_quant_score',
            field=models.IntegerField(blank=True, default=152, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='gre_verbal_score',
            field=models.IntegerField(blank=True, default=150, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='intended_semester',
            field=models.CharField(blank=True, default='F', max_length=5),
        ),
    ]
