# Generated by Django 2.1 on 2021-04-12 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210411_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='toefl_score',
            field=models.IntegerField(blank=True, default=152, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='undergrad_gpa',
            field=models.DecimalField(blank=True, decimal_places=1, default=3.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)]),
        ),
    ]
