# Generated by Django 2.1 on 2021-04-12 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210412_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='gre_awa_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)]),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='gre_quant_score',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='gre_verbal_score',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='intended_semester',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='toefl_score',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='undergrad_gpa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)]),
        ),
    ]
