# Generated by Django 2.1 on 2021-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210412_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='degree',
            field=models.CharField(choices=[('ms', 'MS'), ('phd', 'PhD')], default='ms', max_length=3),
        ),
    ]
