# Generated by Django 2.1 on 2021-04-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210412_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='intended_semester',
            field=models.CharField(blank=True, choices=[('F', 'Fall'), ('S', 'Spring')], max_length=5, null=True),
        ),
    ]
