# Generated by Django 2.1 on 2021-04-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210412_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
