# Generated by Django 2.1.5 on 2021-04-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_siteuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=6),
        ),
    ]
