# Generated by Django 2.1 on 2021-04-17 09:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('user', '0019_auto_20210414_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateAdmissionsProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('degree', models.CharField(choices=[('ms', 'MS'), ('phd', 'PhD')], default='ms', max_length=3)),
                ('gre_verbal_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('gre_quant_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('gre_awa_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0), user.models.awa_score_validator])),
                ('intended_semester', models.CharField(blank=True, choices=[('F', 'Fall'), ('S', 'Spring')], default='F', max_length=5, null=True)),
                ('toefl_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('undergrad_gpa', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=6)),
                ('intended_field', models.CharField(blank=True, max_length=50, null=True)),
                ('is_profile_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
