# Generated by Django 2.1.5 on 2021-06-19 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0020_auto_20210417_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=255)),
                ('recommendation_type', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
