# Generated by Django 2.1.5 on 2021-06-19 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0021_universityrecommendations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniversityRecommendations',
            new_name='UniversityRecommendation',
        ),
    ]
