# Generated by Django 2.1.5 on 2021-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20210519_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofile',
            name='profile_public',
            field=models.BooleanField(default=False),
        ),
    ]
