# Generated by Django 2.1.5 on 2021-05-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_publicprofile_profile_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicprofile',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='publicprofile',
            name='origin',
        ),
    ]
