# Generated by Django 2.1.5 on 2021-05-20 09:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_auto_20210520_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofile',
            name='destination_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='destination_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='origin_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='origin_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
