# Generated by Django 2.1.5 on 2021-05-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_auto_20210520_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofile',
            name='accepted_university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='major',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='profile',
            field=models.TextField(blank=True),
        ),
    ]
