# Generated by Django 2.1.5 on 2021-05-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_auto_20210520_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofile',
            name='profile_updated',
            field=models.BooleanField(default=True),
        ),
    ]
