# Generated by Django 2.1.5 on 2021-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_publicprofile_profile_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicprofile',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
