# Generated by Django 2.1.5 on 2021-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_auto_20210521_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofile',
            name='degree',
            field=models.CharField(choices=[('ms', 'MS'), ('phd', 'PhD')], default='ms', max_length=3),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='intended_semester',
            field=models.CharField(blank=True, choices=[('F', 'Fall'), ('S', 'Spring')], default='F', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='starting_year',
            field=models.IntegerField(blank=True, default=2021),
            preserve_default=False,
        ),
    ]
