# Generated by Django 2.1.5 on 2021-05-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_auto_20210522_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicprofile',
            old_name='intended_semester',
            new_name='starting_semester',
        ),
    ]
