# Generated by Django 2.1.5 on 2021-05-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_auto_20210522_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicprofile',
            name='starting_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
