# Generated by Django 2.1.5 on 2021-06-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_auto_20210601_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to='connect.PublicProfile'),
        ),
    ]
