# Generated by Django 2.1.5 on 2021-06-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0013_auto_20210602_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicprofile',
            name='friends',
        ),
    ]
